### ISSUE TITLE
Add newly added art card to list upon creation without a browser refresh

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-application#112]

**Comment by ZiggyAtl** [comment]
@paulstroot I just want to make sure we're on the same page on this one, as the other issue I made on the subject was noted as a duplicate and closed. And I don't quite understand what this issue is saying. 

The issue was specifically that when I submit something for CoMissioning, it updated the status on the main artwork page, but the status in the Manage Art overview page remained as In Progress. Screenshots below
![Screen Shot 2022-11-07 at 9 16 23 AM](https://user-images.githubusercontent.com/112654923/200332752-70e459ba-41db-4fce-8f65-50cb3e5fa00a.png)

![Screen Shot 2022-11-07 at 9 16 52 AM](https://user-images.githubusercontent.com/112654923/200332781-905607c2-4511-44fc-8c32-eed85aaf7b58.png)

**Comment by ZiggyAtl** [comment]
@paulstroot yes it was correct after the page was refreshed

**Comment by ZiggyAtl** [comment]
@paulstroot a bit more info which could well be related. I deleted an artwork in spotify and it remained in the Manage Art section. I had to refresh the browser for it to disappear.

**Comment by paulstroot** [comment]
That makes sense. The museum app doesn't listen for live updates to Shopify, it loads information from Shopify when the page loads, so if you make an update in Shopify, it won't be reflected in the museum app until you refresh the page. This is pretty standard behavior for web apps. (In Shopify itself, if a purchase is made, it doesn't show up in the admin until you do a refresh.)

**Comment by paulstroot** [comment]
I've uploaded an update. The main art list should be updated automatically now whenever you save or update art.

**Comment by ZiggyAtl** [comment]
@paulstroot thanks. To make sure we're on the same page, do you mean the Manage Art page would update automatically if we approved a Comissioning in shopify? If this is the case this still isn't working, it's not updating. The strange thing is that originally the status in the artwork page would update to Status:Active after Comissioning was approved in Shopify, without the need for a page refresh. But no thats now updating either without a refresh. 

And to make sure we're on the same page, when I refer to a page refresh needed to update it, I'm referring to clicking on the web address and reloading the page to get it to update. If I'm in the app and click between the menu items to go from one page to another, this doesn't update anything.

**Comment by paulstroot** [comment]
No, Anything you update in Shopify will require an update in the museum app. This includes approving a product, marking it as archived, or updating any of the information. The museum app does not have an active connection to Shopify to listen for changes, instead, it re-loads changes when the page is loaded.

The change I just made is that when you create a new piece of art in the museum app and click on "save" or "submit for CoMissioning", you should not need to to reload the page to view the changes in the museum app.

This issue is about the content of the museum app refreshing after you save a change in the museum app, not after you make a change in Shopify, and I think it is working correctly now, right?

**Comment by tbeck** [comment]
Yes... this is working as expected now. Thanks @paulstroot !
